const data = {
    HTTP_CODE: 200,
    HTTP_MESSAGE: 'Success',
    HTTP_RESULT: [
        {
          externalid: 'Accessories',
          itemid: 'Bamboo Watch',
          displayname: 'Bamboo Watch',
          vendorname: 'Chanay, Jeffrey A Esq',
          unitstype: 'PIECE',
          subsidiary: 2,
          itemtype: 'InvtPart',
          includechildren: 'FALSE',
          department: '',
          class: '',
          location: '',
          tracklandedcost: 'TRUE',
          costingmethod: '',
          costcategory: '',
          totalvalue: 0,
          cost: 0,
          purchasedescription: 'Bamboo Watch',
          stockdescription: 'Accessories',
          matchbilltoreceipt: 'FALSE',
          usebins: 'FALSE',
          atpmethod: 'CUMULATIVE_ATP_WITH_LOOK_AHEAD',
          supplyreplenishmentmethod: '',
          alternatedemandsourceitem: '',
          autopreferredstocklevel: 'TRUE',
          reordermultiple: '',
          autoreorderpoint: 0,
          autoleadtime: 'TRUE',
          leadtime: 0,
          safetystocklevel: '',
          safetystockleveldays: 0,
          seasonaldemand: 'TRUE',
          demandmodifier: 0,
          transferprice: 0,
          manufacturer: 'Manufacturer',
          receiptquantity: 0,
          receiptamount: 0,
          receiptquantitydiff: 0,
          preferredlocation: '',
          itembinnumber1: '',
          preferredperlocation: 'TRUE',
          salesdescription: 'SAMPLE SALES DESCRIPTION 2',
          costestimatetype: '',
          costestimate: 0,
          minimumquantity: 1,
          enforceminqtyinternally: '',
          weight: 0,
          weightunit: '',
          quantitypricingschedule: '',
          useMarginalRates: 'TRUE',
          overallquantitypricingtype: '',
          pricinggroup: '',
          salesprice: 0,
          cogsaccount: 226,
          incomeaccount: 54,
          assetaccount: 225,
          taxschedule: 1,
          billpricevarianceacct: '',
          billqtyvarianceacct: '',
          billexchratevarianceacct: '',
          custreturnvarianceaccount: '',
          vendreturnvarianceaccount: '',
          istaxable: 'TRUE',
          purchasetaxcode: '',
          isinactive: 'FALSE',
          //Customized Item  
          custitem_brand: 'SAMPLE',
          custitem_prod_group: 'SAMPLE PRODUCTS',
          custitem_prod_mngr: 'James Butt',
          custitem_stockman: 'Josephine Darakjy',
          custitem_item_class: 'SAMPLE',
          custitem_item_subclass: 'Sample'
        },
        {
          externalid: 'FORCLI0425',
          itemid: 'Black Watch',
          displayname: 'Black Watch',
          vendorname: 'Benton, John B Jr',
          unitstype: 'LICENSE',
          subsidiary: 2,
          itemtype: 'InvtPart',
          includechildren: 'FALSE',
          department: '',
          class: '',
          location: '',
          tracklandedcost: 'TRUE',
          costingmethod: '',
          costcategory: '',
          totalvalue: 0,
          cost: 0,
          purchasedescription: 'Black Watch',
          stockdescription: 'SAMPLEITEM2',
          matchbilltoreceipt: 'FALSE',
          usebins: 'FALSE',
          atpmethod: 'CUMULATIVE_ATP_WITH_LOOK_AHEAD',
          supplyreplenishmentmethod: '',
          alternatedemandsourceitem: '',
          autopreferredstocklevel: 'TRUE',
          reordermultiple: '',
          autoreorderpoint: 0,
          autoleadtime: 'TRUE',
          leadtime: 0,
          safetystocklevel: '',
          safetystockleveldays: 0,
          seasonaldemand: 'TRUE',
          demandmodifier: 0,
          transferprice: 0,
          manufacturer: 'Benton, John B Jr',
          receiptquantity: 0,
          receiptamount: 0,
          receiptquantitydiff: 0,
          preferredlocation: '',
          itembinnumber1: '',
          preferredperlocation: 'TRUE',
          salesdescription: 'SAMPLE SALES DESCRIPTION',
          costestimatetype: '',
          costestimate: 0,
          minimumquantity: 1,
          enforceminqtyinternally: '',
          weight: 0,
          weightunit: '',
          quantitypricingschedule: '',
          useMarginalRates: 'TRUE',
          overallquantitypricingtype: '',
          pricinggroup: '',
          salesprice: 0,
          cogsaccount: 226,
          incomeaccount: 54,
          assetaccount: 225,
          taxschedule: 1,
          billpricevarianceacct: '',
          billqtyvarianceacct: '',
          billexchratevarianceacct: '',
          custreturnvarianceaccount: '',
          vendreturnvarianceaccount: '',
          istaxable: 'TRUE',
          purchasetaxcode: '',
          isinactive: 'FALSE',
          //Customized Item 
          custitem_brand: 'SAMPLE',
          custitem_prod_group: 'SAMPLE PRODUCTS',
          custitem_prod_mngr: 'James Butt',
          custitem_stockman: 'Josephine Darakjy',
          custitem_item_class: 'SAMPLE',
          custitem_item_subclass: 'Sample'
        }
      ]
}

const resdata = ()=>{ 
  return data;
}
module.exports = {resdata} ;